[package]
name = "sendy-framework"
version = "0.1.0"
edition = "2021"

[dependencies]
rsa = { version = "0.9", features = ["sha2"] }
crc32fast = "1.3"

tokio = { version = "1.29", features = ["net", "macros", "rt", "time", "sync"] }
dashmap = "5.5"
bytes = "1.4"
futures = "0.3"

log = "0.4"

bytemuck = { version = "1.13", features = ["derive"] }
byteorder = "1.4"
thiserror = "1.0"
hibitset = "0.6"
serde = "1.0"
serde_repr = "0.1"
